### ISSUE TITLE
Create rectangle still not implemented?

### ISSUE THREAD

**Issue by armeya25** [louisnw01/lightweight-charts-python#287] opened 2024-02-10 08:00 UTC
### Question

Plz,
Add support to draw rectangle in lightweight charts,
I am still waiting for it to appear in this library,

I have seen many requests to implement it,
But still didn't find any progress,

Thanks for ur great work

**Comment by louisnw01** [comment] 2024-02-10 20:00
Hey @armeya25,

Rectangle drawings will require the use of plugins which were recently added to the original Lightweight Charts library; this will require a complete rework of the JavaScript side of this library, which is why it hasnt been implemented yet and likely wont be for some time.

Anyway, closing as duplicate of #180.

Louis

**Closed by louisnw01** 2024-02-10 20:00 UTC
