### ISSUE TITLE
create_line on the same chart results in unnecessary hide legend 

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#85] opened 2023-08-26 19:25 UTC
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/3427f0ac-50ab-46b4-992c-939d35e98f61)

The more overlays you add there is duplicated hide indicator icon that appears
used the 4_line_indicators example

**Comment by louisnw01** [comment] 2023-08-26 21:44
Duplicate of #75, will be fixed in the next update.

Louis

**Closed by louisnw01** 2023-08-26 21:44 UTC
