### ISSUE TITLE
Feedback on v1.0.14

### ISSUE THREAD

**Issue by emma-uw** [louisnw01/lightweight-charts-python#44] opened 2023-07-17 09:12 UTC
Hey, first of all drawings feature is insane. Thank you!

Some minor suggestions:
1. Ray line is not set in place after the initial click. Instead the ray is created under the mouse and being dragged around. Second click will set the desired position. Seems counterintuitive. Is this intended behaviour or just a bug?
2. `"cmd-Z will delete the last drawing."`. Don't think `event.metaKey` is detected correctly (as win key) while doing that on windows. Maybe replace it with `Ctrl+Z` in windows case?
3. If you select horizontal line from the toolbox and then select something else without making one, it will create new horizontal line on click regardless. Example with trendline:
![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/135511356/8e6c720b-7fac-4049-9c9d-1af637d65368)
4. What's your opinion on making drawings list accessible similar to lines? This will allow saving drawings between sessions, making alerts, removing them programmatically etc.

**Comment by louisnw01** [comment] 2023-07-17 12:19
Hey @emma-uw,

number 2 and 3 are bugs; I'll change the key command to either Cmd-Z or Ctrl-Z, and the duplicate drawings were caused by the drawing actions not being properly unsubscribed.

As for 1; I considered both options, but thought that as ray lines contain both time scale and price scale information similar to trendlines and unlike horizontal lines, that two clicks would make more sense. But if this is unconventional, i'm happy to change it to a single click. Anyone else got an opinion? 🙂

As for 4; this is definitely in the pipeline, but I was considering a way to save the chart as a binary file which could then be loaded into a fresh chart object. Would require some pretty sigificant refactoring to allow it to work across all objects.

The issue I see with using a drawings list to set alerts and removing them programatically, is how do you differenciate between them? There would be no id for the user to reference back to, as it has been drawn in by hand. Happy to hear any solutions to this!

Additionally, have to tried out the `interactive` parameter for horizontal lines yet? They are similar to what you are asking for, however only apply to horizontal lines and not trends or rays. I imaged their usefulness being for setting stop losses and limit orders, but they could definitely be used for alerts.

Thanks!

**Comment by louisnw01** [comment] 2023-07-17 14:08
2 and 3 are fixed in the Latest version (v1.0.14.1).

**Comment by emma-uw** [comment] 2023-07-17 18:21
Thanks for the fix!

`The issue I see with using a drawings list to set alerts and removing them programatically, is how do you differenciate between them?`
This is true actually. Maybe I am just overthinking it. Mostly I was trying to preserve drawings while switching in between tickers (same chart instance) and save them between sessions, but didn't come up with a easy solution. Apart from passing the list directly or maybe using localstorage. Managing lines, markers etc is pretty trivial atm, that's why I asked initially. 

`Additionally, have to tried out the interactive parameter for horizontal lines yet?`
Yes, it's pretty good. I am planning on using it to adjust my orders eventually.

Thank you.

**Comment by louisnw01** [comment] 2023-07-17 23:42
> Mostly I was trying to preserve drawings while switching in between tickers (same chart instance) and save them between sessions

I hadn't considered this; very good point. Maybe a `drawings` method could be used, but I can't think of a use case other than swapping between tickers. 

How about a `save_drawings` method, which could be used as:

```python
async def on_search(symbol):
    self.chart.save_drawings(id=self.chart.topbar['symbol'].value)
```

Which saves those drawings to a dictionary item within the chart object, under the key of the id. And then upon searching the same symbol:

```python
async def on_search(symbol):
   self.chart.load_drawings(id=symbol)
```

___

And then for persistence between instances, maybe an `export_drawings` method could save a binary:

```python
chart.show(block=True)
# Once the chart has exited
chart.export_drawings('saves/chart_drawings.bin')
```

Which saves all drawings within the chart to a binary file, and could be loaded the next time the code is run with something like `chart.load_drawings('saves/chart_drawings.bin')`

I think implementing something like this is absolutely necessary, but I'm not sure if this is the best way to do it; let me know what you think either way.

**Comment by emma-uw** [comment] 2023-07-18 09:04
@louisnw01 Yeah, usually it's better to leave save/load handling to the user. So normal `chart.drawings()` to get the list and `chart.set_drawings()` to set the list would've been fine. But if preserving them is the only use case we have, your solution looks fine.

Another thought. Functionality and usability wise is there even a big difference between manually drawn lines and lines created by `line.set(`)? Maybe treating them as `chart.lines()` would make some sense as well? Moving them into the main list while adding `drawing=True` flag. Unifying types and constructors so you can do something like `line.set(type=ray, ...)` etc. Can also give the user an ability to set a name for lines created programatically and maybe double clicking the drawing would promt you to type a name for it. Then user can further modify them however he wants.

Thank you.

**Comment by louisnw01** [comment] 2023-07-18 16:48
@emma-uw I'll start coding it up as `save_drawings` for now. If you (or anyone else) can think of another use case, then i'd be happy to revert back or include both.

Fundamentally, ray lines and trendlines are lines, however there is quite a bit of calculation that goes into making them which differenciates them. Because of the way Lightweight Charts work, each individual point between the lines needs to be included in the data, and it can't include weekends/holidays or you'll end up with gaps on the chart. This is so that they can be dragged around from any point on the line, as Lightweight Charts doesnt recognize that there is a line at the cursor if there is not a datapoint at that point in time. 

This is why I chose to use a different method rather than `line.set`, because trendlines, raylines and lines all need different data to be given to them. I could give `line.set` a variable number of arguments so that they can all be created from `line.set`, but a little worried that this would be confusing? Maybe i'm overthinking it.

If i were to make the drawing list accessible, it would probably be better to include them as a seperate list; lines are typically used for indicators, and having all your indicators and trendlines in one list might also be confusing.

Lines created programatically can already be named within the `set` method, but I think being able to name drawings is a great idea; this would solve the issue of identification, but i'm still not too sure what the use case for this would be.

Thanks!

**Comment by Kevin9876** [comment] 2023-07-20 01:10
Mouse line drawing ray lines and trendlines are very important functions in trading. I hope that in the next update, both the ray line and the trendline can be created from line.set, but it cannot be line.set, so change the name to draw.set or tool.set. Thanks!

**Comment by louisnw01** [comment] 2023-07-20 20:57
Hey @emma-uw,

The latest version implements a basic version of saving drawings. Let me know what you think!

Louis

**Comment by louisnw01** [comment] 2023-07-20 21:00
> Mouse line drawing ray lines and trendlines are very important functions in trading. I hope that in the next update, both the ray line and the trendline can be created from line.set, but it cannot be line.set, so change the name to draw.set or tool.set. Thanks!

Hey @Kevin9876,

Not entirely sure what you mean, but at the moment you can use the `trend_line` and `ray_line` methods to programatically create drawings.

**Comment by Kevin9876** [comment] 2023-07-21 01:46
What I mean is: the line drawn with the mouse through the toolbox, not the line drawn by the program. The lines drawn by the mouse or the program should be accessible by the program. It is best to be able to right-click on the line drawn (whether by the mouse or the program) to set an alarm or place an order. In the current version, the lines drawn with the mouse through the toolbox cannot be accessed by the program.

**Comment by emma-uw** [comment] 2023-07-22 11:42
@louisnw01 Hey, just tested it works very good. Presistent between symbols and saving/loading from file is pretty easy. Thank you! 

One thing is that prob good to mention somewhere in docs that `chart.toolbox.load_drawings()` call should be after `chart.set()` overwise no drawings will be loaded. But maybe that's just me. Also drawings are now kinda accessible through the dict for anyone willing to expand for alerts and etc. Can even convert them into normal lines pretty easily hah. Thanks again good sir.

@Kevin9876 check out the latest version. It's now possible to get the dictinoary with all your drawings after modifying the library a little with something like ```def get_drawings(self): return self._saved_drawings```. And then go wild.

**Comment by emma-uw** [comment] 2023-07-22 11:52
Also since drawings are presistent now, will probably need something better than ctrl+z to manage all the complex charts. Maybe right-click -> delete?

**Comment by louisnw01** [comment] 2023-07-22 15:28
@emma-uw no worries; and yes I think a better way to delete lines would make sense, I'll take a look into this. 

Louis

**Comment by louisnw01** [comment] 2023-07-24 16:05
> Also since drawings are presistent now, will probably need something better than ctrl+z to manage all the complex charts. Maybe right-click -> delete?

Latest version now has context menus for each drawing, so you can delete them independently.

**Comment by emma-uw** [comment] 2023-07-25 16:42
@louisnw01 sounds great, thank you! Can prob close that issue since everything is solved now.

**Closed** 2023-07-26 10:06 UTC
Labels: bug, enhancement
