### ISSUE TITLE
Negative values are displayed incorrectly since the last update

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#28] opened 2023-06-29 11:07 UTC
Thanks for the latest update. I'm currently checking newest additions.

Some things:
1)
There is a bug in new clear_markers() function:

code now:
```self.run_script(f'''{self.id}.markers = []; {self.id}.series.setMarkers([]])''')```
fixed code:
```self.run_script(f'''{self.id}.markers = []; {self.id}.series.setMarkers([])''')```

2)

Negative values are displayed incorrectly since last update
![Unbena3nnt](https://github.com/louisnw01/lightweight-charts-python/assets/104310309/04943b4a-a933-4fdb-941b-62bd94cf71d9)

3)

I can't get a legend to show in a subchart. I think this did not work in previous version too?

**Comment by louisnw01** [comment] 2023-06-29 13:57
Hey @Zartexo, your welcome, thanks for the suggestions!

Number 3 appears to be related to a lack of candle data rather than a subchart. I'll publish a fix for that and number 1 ASAP.

I'm unable to reproduce the negative value error; could you try adding this code to the line indicators example and see if it still occurs?

```python
sma_data['value'] = sma_data['value'] * -1 # Flips the data to negative values
```

**Comment by Zartexo** [comment] 2023-06-29 14:19
@louisnw01 I added the line and could reproduce the visual error.

Downgrade to v 1.0.12 fixes the issue. So it's related to the latest update.

The code i used:
```
import pandas as pd
from lightweight_charts import Chart


def calculate_sma(data: pd.DataFrame, period: int = 50):
    def avg(d: pd.DataFrame):
        return d['close'].mean()
    result = []
    for i in range(period - 1, len(data)):
        val = avg(data.iloc[i - period + 1:i])
        result.append({'time': data.iloc[i]['date'], 'value': val})
    return pd.DataFrame(result)


if __name__ == '__main__':

    chart = Chart()

    df = pd.read_csv('ohlcv.csv')
    chart.set(df)

    line = chart.create_line()
    sma_data = calculate_sma(df)
    sma_data['value'] = sma_data['value'] * -1  # Flips the data to negative values
    line.set(sma_data)

    chart.show(block=True)
```

**Comment by louisnw01** [comment] 2023-06-29 18:06
1 and 3 are fixed in the latest version (1.0.13.2).

**Comment by Zartexo** [comment] 2023-06-29 18:19
I am using Win 11 Pro and also tried on Win 10 Pro. Same result

Not sure which web console. This is the element info:
![Screenshot 2023-06-29 201842](https://github.com/louisnw01/lightweight-charts-python/assets/104310309/175fbc28-e9b4-466a-9705-ff3cff59ce99)

**Comment by Zartexo** [comment] 2023-06-29 18:35
@louisnw01 I just tested the hotfix.

now line 67 in chart.py crashes my program
`self.run_script(JS['toolbox'])`

**Comment by louisnw01** [comment] 2023-06-29 18:39
Fixed in the latest version.

**Comment by Zartexo** [comment] 2023-06-29 19:10
Thank you @louisnw01 🥇 

Got the subchart legend working. Negative values are displayed correctly in the legend btw

**Comment by louisnw01** [comment] 2023-06-29 22:35
Hmm, sounds like a rendering issue if the values are correct in the legend.

To view the web console, with `debug=True`, right click the chart window and open the inspector. then go to the Console tab.

**Comment by Zartexo** [comment] 2023-07-01 06:36
It's empty :/

**Comment by louisnw01** [comment] 2023-07-01 12:23
I wonder if its to do with the autoScaleInfoProvider which I updated in the latest update. Are you using `scale_candles_only`?

**Comment by Zartexo** [comment] 2023-07-01 14:43
No, i am not using it

**Comment by louisnw01** [comment] 2023-07-01 15:52
Hmm!

It's definitely a  formatting issue with lightweight charts; the values that get displayed appear to be [negative ascii code](https://gsamaras.wordpress.com/code/negative-ascii-codes/).

But as you said it works fine in the previous version, I've scanned through the diff but can't find anything unusual.

Reinstalling my windows VM and I'll try to reproduce.

**Comment by Zartexo** [comment] 2023-07-03 13:30
Just tested it. It's displayed correctly again. Thank you a lot @louisnw01 for fixing this tricky bug 👍

**Closed** 2023-07-03 13:30 UTC
Labels: bug
