### ISSUE TITLE
[BUG] timescale sync across multiple timeframes

### ISSUE THREAD

**Issue by jlixfeld** [louisnw01/lightweight-charts-python#238] opened 2023-12-30 17:12 UTC
### Expected Behavior

In TradingView, when grabbing a chart and moving it around, all other charts preserve the data in the viewport relative to the timescale of selected/dragged chart, and also relative to it's last bar:

https://github.com/louisnw01/lightweight-charts-python/assets/17339017/891d802b-930f-4540-a94b-c18f8bc01020

### Current Behaviour

In Lightweight Charts Python, this behaviour is different, and I'm wondering if there's a way to have this functionality synced up.

Unsure if this is related to #147

https://github.com/louisnw01/lightweight-charts-python/assets/17339017/eadb71fc-c81e-4bdb-ad49-e92c91dba7b7

### Reproducible Example

The code and attached CSVs will load data for the same symbol across two different timeframes.  The left chart is a 15 minute timeframe.  The right chart is a 1 minute timeframe.

[1min.csv](https://github.com/louisnw01/lightweight-charts-python/files/13798700/1min.csv)
[15mins.csv](https://github.com/louisnw01/lightweight-charts-python/files/13798702/15mins.csv)

```python
from lightweight_charts import Chart
from pandas import read_csv

if __name__ == "__main__":
    chart_15m = Chart(inner_width=0.5, inner_height=0.5)
    chart_1m = chart_15m.create_subchart(sync=True)

    chart_15m.set(read_csv("15mins.csv"))
    chart_1m.set(read_csv("1min.csv"))

    chart_15m.show(block=True)
```

### Environment

```markdown
- OS: macOS 14.2.1
- Library: 1.0.18.8
```

**Comment by louisnw01** [comment] 2023-12-30 17:32
Hey @jlixfeld,

This is a duplicate of #147; not a bug, lightweight charts simply doesnt offer this fuctionality at the moment.

Louis

**Closed by louisnw01** 2023-12-30 17:32 UTC
Labels: bug
